language: java
jdk:
- oraclejdk8
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username:
    secure: AybugC3sfV+96CNMiuwRUSmZHv0xVWpzqtUhPnJfjvCUM9jsDHyZvlZXtYz57qYz9QyOg26EYFis9Y11tfmGdU+HxTfEyglxrTf15aba+PEL8Iqb6ysMpLD1EAlGqCpW27PKm9w+D+tsEYgW2JD2Gjp/0spMV/eyGIE97cp8mrw/g7+t/MTo4BasKDqNK1gRYQ6huH+8F+2af+9Ap7SAOza54KEb1kR7s7vzWo5MvU8pVJl1gfhMT4AGswxtZmzijNRWK/iNH5IIPnKT08b8Qnen9t4xufbusFdx5+g8j6cYcl/SaFCFV14kGcAYR2O6cHYS1XtNS3Cc7AN7T73RunXoqn8pE/Drz30ONCRnJoYjgdFn8YOS/3sH5Ts70LrOp3coDQ3nTuKyzX7Utd0u6HDoE8lNdpVBuwXPmtbqUsO64Lcdp38cgNi/uF4HrFzqcxRUYx64siBZSJt7ud/jzcgVVPVYbKsqassb0rXWCgTInvJ8SuCe8iy/lIBGtFy9j62bSOw3lwEv7jzNakSrN0rrSpgXCBSrKwQiM0SiSJcW3kDNURGcV+5vEHCxVLT+Kz5VfJc6ttNbN0wibfWzRQujRstMem6Uy6j6+R6F1rebBL2pf2EG4sH3C3znODz01hF3TevPDUBHJNhtUkrsr5NyYnmbihgveMOITl8z1Mw=
  password:
    secure: tM8E+hOL1Awml+bSYAsZ26L/XjPzfmI0idmzFYpj0E1ouDmhUw5VtZ8NH2YceL1I6XDiQv3MizPEkfjI2BLRsLqCSJirVMj3ClhEsj+QZlmW/0X6CpXV2BXYJL2VyTq6PZttz0I+jQzTNVuRXYXs47v9xW9JeKQG7gZYJsS/dSIWxKCzr+ncIYRE1PtI1hlXtR/WWxZsXBRhhO7CQzyeoqMrTQnUUiCvuuYjdDVzIkOgLVgpMa/OfbV8wf53U/QOIVW3Ush3VrI+UL88KtjFCffldr9WNirpLIHYAQFa2Hpn5lTTkQAF5KiKLuchO0P9hM3fhs5HQ5iYkO/Ic8AtxbW9xfxLuS1qICSW/R7POnZRd8WP1LMCYSL67XZdMVGM2cEd+0Jxj6lCBebKhUCjWdSYZL5OUNhXyAB2Zq+YfxYKAsSmV5B998rTbDrJd4KFJXOZlYquvVji1SNK2Kxt8SpP5ov/yroCD4qKwv489yrR8A1Xu1syzirV+/lgS+brsuBXrlFSHFZS99sYGTXuk1lAdAOjpKKcnuDI5gbJJ3M3rHsrOWZXUkxtyXxIH5RP8c2+SiSadJWcga3Z+lrhSllXsrSgEzC2c7Eod+0p9LrekPUn75+ZhBQ+qTXch7da4Dz/nfeCrTJSBLkuWy5kxDEPJcuK9xGvbDsOfvil2k8=
  organization: zhuangx-cc
  space: development
  on:
    repo: zhuang-xie/Image-Gallery-Application
